# Generated by Django 6.0.3 on 2026-04-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('doc_id', models.AutoField(db_column='Doc_ID', primary_key=True, serialize=False)),
                ('doc_tipo', models.CharField(db_column='Doc_Tipo', max_length=7)),
                ('doc_serie', models.CharField(db_column='Doc_Serie', max_length=10)),
                ('doc_correlativo', models.IntegerField(db_column='Doc_Correlativo')),
                ('doc_fechaemision', models.DateTimeField(blank=True, db_column='Doc_FechaEmision', null=True)),
                ('doc_monto', models.DecimalField(db_column='Doc_Monto', decimal_places=2, max_digits=10)),
                ('doc_estado', models.CharField(blank=True, db_column='Doc_Estado', max_length=7, null=True)),
            ],
            options={
                'db_table': 'documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('loc_id', models.AutoField(db_column='Loc_ID', primary_key=True, serialize=False)),
                ('loc_nombre', models.CharField(db_column='Loc_Nombre', max_length=100)),
                ('loc_direccion', models.CharField(blank=True, db_column='Loc_Direccion', max_length=150, null=True)),
                ('loc_distrito', models.CharField(blank=True, db_column='Loc_Distrito', max_length=100, null=True)),
            ],
            options={
                'db_table': 'local',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('metpag_id', models.AutoField(db_column='MetPag_ID', primary_key=True, serialize=False)),
                ('metpag_descripcion', models.CharField(db_column='MetPag_Descripcion', max_length=50)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('paq_id', models.AutoField(db_column='Paq_ID', primary_key=True, serialize=False)),
                ('paq_nombre', models.CharField(db_column='Paq_Nombre', max_length=100)),
                ('paq_precio', models.DecimalField(db_column='Paq_Precio', decimal_places=2, max_digits=10)),
                ('paq_descripcion', models.TextField(blank=True, db_column='Paq_Descripcion', null=True)),
                ('paq_maxinvitados', models.IntegerField(blank=True, db_column='Paq_MaxInvitados', null=True)),
                ('paq_tiempohoras', models.IntegerField(blank=True, db_column='Paq_TiempoHoras', null=True)),
            ],
            options={
                'db_table': 'paquete',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(db_column='Usu_ID', primary_key=True, serialize=False)),
                ('usu_nombres', models.CharField(db_column='Usu_Nombres', max_length=100)),
                ('usu_apellidos', models.CharField(db_column='Usu_Apellidos', max_length=100)),
                ('usu_tipodocumento', models.CharField(db_column='Usu_TipoDocumento', max_length=3)),
                ('usu_numdocumento', models.CharField(db_column='Usu_NumDocumento', max_length=20)),
                ('usu_email', models.CharField(blank=True, db_column='Usu_Email', max_length=100, null=True)),
                ('usu_telefono', models.CharField(blank=True, db_column='Usu_Telefono', max_length=20, null=True)),
                ('usu_rol', models.CharField(db_column='Usu_Rol', default='Cliente', max_length=50)),
                ('usu_fecharegistro', models.DateTimeField(auto_now_add=True, db_column='Usu_FechaRegistro', null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('bol_id', models.AutoField(db_column='Bol_ID', primary_key=True, serialize=False)),
                ('bol_tipodocumento', models.CharField(db_column='Bol_TipoDocumento', max_length=3)),
                ('bol_numdocumento', models.CharField(db_column='Bol_NumDocumento', max_length=20)),
                ('bol_nombrecliente', models.CharField(db_column='Bol_NombreCliente', max_length=150)),
                ('doc', models.ForeignKey(db_column='Doc_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.documento')),
            ],
            options={
                'db_table': 'boleta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('fac_id', models.AutoField(db_column='Fac_ID', primary_key=True, serialize=False)),
                ('fac_ruc', models.CharField(db_column='Fac_RUC', max_length=20)),
                ('fac_razonsocial', models.CharField(db_column='Fac_RazonSocial', max_length=150)),
                ('fac_direccionfiscal', models.CharField(blank=True, db_column='Fac_DireccionFiscal', max_length=200, null=True)),
                ('doc', models.ForeignKey(db_column='Doc_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.documento')),
            ],
            options={
                'db_table': 'factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('dj_id', models.AutoField(db_column='DJ_ID', primary_key=True, serialize=False)),
                ('dj_especialidad', models.CharField(blank=True, db_column='DJ_Especialidad', max_length=100, null=True)),
                ('dj_activo', models.IntegerField(blank=True, db_column='DJ_Activo', default=1, null=True)),
                ('usu', models.ForeignKey(db_column='Usu_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'dj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(db_column='Cli_ID', primary_key=True, serialize=False)),
                ('cli_observaciones', models.TextField(blank=True, db_column='Cli_Observaciones', null=True)),
                ('usu', models.ForeignKey(db_column='Usu_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('adm_id', models.AutoField(db_column='Adm_ID', primary_key=True, serialize=False)),
                ('adm_rol', models.CharField(blank=True, db_column='Adm_Rol', max_length=50, null=True)),
                ('usu', models.ForeignKey(db_column='Usu_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'administrador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('ususis_id', models.AutoField(db_column='UsuSis_ID', primary_key=True, serialize=False)),
                ('ususis_username', models.CharField(db_column='UsuSis_Username', max_length=100, unique=True)),
                ('password', models.CharField(db_column='UsuSis_Password', max_length=255)),
                ('ususis_estado', models.CharField(db_column='UsuSis_Estado', default='Activo', max_length=8)),
                ('usu', models.ForeignKey(db_column='Usu_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'usuario_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ven_id', models.AutoField(db_column='Ven_ID', primary_key=True, serialize=False)),
                ('ven_fechaevento', models.DateField(db_column='Ven_FechaEvento')),
                ('ven_duracionhoras', models.IntegerField(db_column='Ven_DuracionHoras')),
                ('ven_montototal', models.DecimalField(db_column='Ven_MontoTotal', decimal_places=2, max_digits=10)),
                ('ven_estado', models.CharField(blank=True, db_column='Ven_Estado', max_length=10, null=True)),
                ('ven_fecharegistro', models.DateTimeField(blank=True, db_column='Ven_FechaRegistro', null=True)),
                ('adm', models.ForeignKey(db_column='Adm_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.administrador')),
                ('cli', models.ForeignKey(db_column='Cli_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.cliente')),
                ('dj', models.ForeignKey(db_column='DJ_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.dj')),
                ('loc', models.ForeignKey(db_column='Loc_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.local')),
                ('paq', models.ForeignKey(db_column='Paq_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.paquete')),
            ],
            options={
                'db_table': 'venta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('regeve_id', models.AutoField(db_column='RegEve_ID', primary_key=True, serialize=False)),
                ('regeve_nombrelugar', models.CharField(blank=True, db_column='RegEve_NombreLugar', max_length=100, null=True)),
                ('regeve_fecha', models.DateField(blank=True, db_column='RegEve_Fecha', null=True)),
                ('regeve_duracionhoras', models.IntegerField(blank=True, db_column='RegEve_DuracionHoras', null=True)),
                ('regeve_cliente', models.CharField(blank=True, db_column='RegEve_Cliente', max_length=150, null=True)),
                ('ven', models.ForeignKey(db_column='Ven_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.venta')),
            ],
            options={
                'db_table': 'registro_evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pag_id', models.AutoField(db_column='Pag_ID', primary_key=True, serialize=False)),
                ('pag_monto', models.DecimalField(db_column='Pag_Monto', decimal_places=2, max_digits=10)),
                ('pag_referencia', models.CharField(blank=True, db_column='Pag_Referencia', max_length=100, null=True)),
                ('pag_estado', models.CharField(blank=True, db_column='Pag_Estado', max_length=9, null=True)),
                ('pag_fecha', models.DateTimeField(blank=True, db_column='Pag_Fecha', null=True)),
                ('metpag', models.ForeignKey(db_column='MetPag_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.metodopago')),
                ('ven', models.ForeignKey(db_column='Ven_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.venta')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('eva_id', models.AutoField(db_column='Eva_ID', primary_key=True, serialize=False)),
                ('eva_tipo', models.CharField(db_column='Eva_Tipo', max_length=7)),
                ('eva_calificacion', models.JSONField(blank=True, db_column='Eva_Calificacion', null=True)),
                ('eva_comentario', models.TextField(blank=True, db_column='Eva_Comentario', null=True)),
                ('ven', models.ForeignKey(db_column='Ven_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.venta')),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='ven',
            field=models.ForeignKey(db_column='Ven_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('doc_serie', 'doc_correlativo')},
        ),
    ]
